spring:
  application:
    name: eureka-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:heyic/SpringcloudConfig.git
          search-paths: respo
          username: heyic
          password: 131796he
      label: master


server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka

